@startuml
autonumber
title Add SubMenu Item\n in CMS v2

actor User
participant FrontendCMSv2
participant Radiality_BE
database RethinkDB

User -> FrontendCMSv2 : Add\n SubMenu Item
FrontendCMSv2 -> Radiality_BE : CREATE child\n (<b>parent_ID</b>)
Radiality_BE -> RethinkDB : UPDATE Parent with\n <b>child_ID</b> record\n in 'menu' table
Radiality_BE -> RethinkDB : READ records\n in 'menu' table
RethinkDB --> Radiality_BE : 'menu' table cursor
Radiality_BE -> Radiality_BE : Create list (?)
Radiality_BE --> FrontendCMSv2 : List of all items
FrontendCMSv2 -> FrontendCMSv2 : Parse response\n and create 'tree' (?)
FrontendCMSv2 -> FrontendCMSv2 : Render UI
FrontendCMSv2 --> User : Show menu

@enduml